[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4"
env_logger = "0.11.5"
game-of-life = { path = "../game-of-life/" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.139"
